import { useEffect, useMemo, useState } from "react";
import DOMPurify from "dompurify";
import RichTextEditor from "@/components/RichTextEditor";
import { AdminPostItem, createPost, EditorialChannel, ContentFormat, EditorialStatus, getTaxonomy, Taxonomy, updatePost } from "@/lib/posts";
import { getErrorMessage } from "@/lib/errors";
import { useNavigate } from "react-router-dom";

type Props = { open: boolean; onClose: () => void; mode?: "create"|"edit"; initialData?: AdminPostItem|null; onSuccess?: () => void|Promise<void> };
const empty = { title:"", slug:"", excerpt:"", content:"", channel:"CONTENT" as EditorialChannel, format:"ARTICLE" as ContentFormat, status:"DRAFT" as EditorialStatus, categoryId:"", tags:"", imageUrl:"", imageAlt:"", imageCaption:"", imageCredit:"", seoTitle:"", seoDescription:"", isFeatured:false, featuredPriority:"0", authorProfileId:"" };
export default function NewPostModal({ open, onClose, mode="create", initialData, onSuccess }: Props) {
  const [form, setForm] = useState(empty); const [imageFile,setImageFile]=useState<File|null>(null); const [taxonomy,setTaxonomy]=useState<Taxonomy|null>(null); const [saving,setSaving]=useState(false); const navigate=useNavigate();
  useEffect(()=>{ if(open) getTaxonomy().then(setTaxonomy); },[open]);
  useEffect(()=>{ if(!open) return; if(mode==="edit"&&initialData) setForm({ title:initialData.title||"", slug:initialData.slug||"", excerpt:initialData.excerpt||"", content:initialData.content||"", channel:initialData.channel||"CONTENT", format:initialData.format||"ARTICLE", status:initialData.status||"DRAFT", categoryId:initialData.category?.id?String(initialData.category.id):"", tags:(initialData.tags||[]).map(t=>t.name).join(", "), imageUrl:initialData.imageUrl||"", imageAlt:initialData.imageAlt||"", imageCaption:initialData.imageCaption||"", imageCredit:initialData.imageCredit||"", seoTitle:initialData.seoTitle||"", seoDescription:initialData.seoDescription||"", isFeatured:Boolean(initialData.isFeatured), featuredPriority:String(initialData.featuredPriority??0), authorProfileId:initialData.author?.id?String(initialData.author.id):"" }); else setForm(empty); setImageFile(null); },[open,mode,initialData]);
  const preview=useMemo(()=>imageFile?URL.createObjectURL(imageFile):form.imageUrl,[imageFile,form.imageUrl]); if(!open)return null;
  const set=(key:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(v=>({...v,[key]:e.target.value}));
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);try{const payload={...form,content:DOMPurify.sanitize(form.content),categoryId:form.categoryId?Number(form.categoryId):null,authorProfileId:form.authorProfileId?Number(form.authorProfileId):undefined,tagNames:form.tags.split(",").map(x=>x.trim()).filter(Boolean),featuredPriority:form.isFeatured?Number(form.featuredPriority):null,imageFile,postType:form.format==="RECIPE"?"Receita":"Artigo"}; const saved=mode==="edit"&&initialData?await updatePost(initialData.id,payload):await createPost(payload); await onSuccess?.();onClose();if(mode==="create"&&saved.status==="PUBLISHED")navigate(saved.canonicalPath);}catch(err){alert(getErrorMessage(err));}finally{setSaving(false)}}
  return <div className="fixed inset-0 z-[1000] flex items-center justify-center bg-black/50 p-4"><div className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white shadow-xl"><header className="sticky top-0 z-10 flex justify-between bg-emerald-600 px-6 py-4 text-white"><div><h2 className="font-semibold">{mode==="edit"?"Editar conteúdo":"Novo conteúdo"}</h2><p className="text-xs text-emerald-50">Conteúdo 2.0</p></div><button type="button" onClick={onClose}>Fechar</button></header><form onSubmit={submit} className="space-y-5 p-6">
    <div className="grid gap-4 md:grid-cols-2"><Field label="Título"><input required value={form.title} onChange={set("title")} className="input"/></Field><Field label="Slug"><input value={form.slug} onChange={set("slug")} className="input" placeholder="gerado pelo título"/></Field><Field label="Canal"><select value={form.channel} onChange={set("channel")} className="input"><option value="CONTENT">Conteúdos</option><option value="BLOG">Blog</option></select></Field><Field label="Formato"><select value={form.format} onChange={set("format")} className="input"><option value="ARTICLE">Artigo</option><option value="RECIPE">Receita</option></select></Field><Field label="Status"><select value={form.status} onChange={set("status")} className="input"><option value="DRAFT">Rascunho</option><option value="PUBLISHED">Publicado</option><option value="ARCHIVED">Arquivado</option><option value="SCHEDULED">Agendado (preparado)</option></select></Field><Field label="Categoria"><select value={form.categoryId} onChange={set("categoryId")} className="input"><option value="">Sem categoria</option>{taxonomy?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Tags (separadas por vírgula)"><input value={form.tags} onChange={set("tags")} className="input"/></Field><Field label="Autoria pública"><select value={form.authorProfileId} onChange={set("authorProfileId")} className="input"><option value="">Juliana (padrão)</option>{taxonomy?.authors.map(a=><option key={a.id} value={a.id}>{a.displayName}</option>)}</select></Field></div>
    <Field label="Resumo editorial"><textarea required={form.status==="PUBLISHED"} value={form.excerpt} onChange={set("excerpt")} className="input min-h-24" maxLength={500}/></Field><Field label="Conteúdo"><RichTextEditor value={form.content} onChange={content=>setForm(v=>({...v,content}))}/></Field>
    <div className="grid gap-4 md:grid-cols-2"><Field label="Imagem URL"><input value={form.imageUrl} onChange={set("imageUrl")} className="input"/></Field><Field label="Arquivo de imagem"><input type="file" accept="image/*" onChange={e=>setImageFile(e.target.files?.[0]||null)} className="input"/></Field><Field label="Texto alternativo"><input value={form.imageAlt} onChange={set("imageAlt")} className="input"/></Field><Field label="Legenda"><input value={form.imageCaption} onChange={set("imageCaption")} className="input"/></Field><Field label="Crédito"><input value={form.imageCredit} onChange={set("imageCredit")} className="input"/></Field>{preview&&<img src={preview} alt={form.imageAlt||"Prévia"} className="max-h-44 w-full rounded object-cover"/>}</div>
    <div className="grid gap-4 md:grid-cols-2"><Field label="Título SEO"><input value={form.seoTitle} onChange={set("seoTitle")} className="input"/></Field><Field label="Descrição SEO"><textarea value={form.seoDescription} onChange={set("seoDescription")} className="input" maxLength={320}/></Field></div>
    <div className="flex gap-4"><label className="flex items-center gap-2"><input type="checkbox" checked={form.isFeatured} onChange={e=>setForm(v=>({...v,isFeatured:e.target.checked}))}/>Destaque</label>{form.isFeatured&&<input type="number" min="0" value={form.featuredPriority} onChange={set("featuredPriority")} className="input w-28" aria-label="Prioridade do destaque"/>}</div>
    <div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded border px-4 py-2">Cancelar</button><button disabled={saving} className="btn-primary">{saving?"Salvando...":form.status==="DRAFT"?"Salvar rascunho":"Salvar conteúdo"}</button></div>
  </form></div></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium text-emerald-900">{label}<div className="mt-1">{children}</div></label>}
